// <auto-generated />
using System;
using DrakthulJelita.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrakthulJelita.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228120857_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DrakthulJelita.Web.Models.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WowClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WowName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("WowClassId");

                    b.HasIndex("WowClassId", "WowName");

                    b.ToTable("Screenshots");
                });

            modelBuilder.Entity("DrakthulJelita.Web.Models.WowClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WowClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#C41E3A",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "death knight"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#A330C9",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "demon hunter"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FF7C0A",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "druid"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#33937F",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "evoker"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#AAD372",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "hunter"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#3FC7EB",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "mage"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#00FF98",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "monk"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#F48CBA",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "paladin"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#FFFFFF",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "priest"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#FFF468",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "rogue"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#0070DD",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "shaman"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#8788EE",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "warlock"
                        },
                        new
                        {
                            Id = 13,
                            Color = "#C69B6D",
                            CreatedAt = new DateTime(2025, 4, 12, 9, 5, 46, 0, DateTimeKind.Utc),
                            Name = "warrior"
                        });
                });

            modelBuilder.Entity("DrakthulJelita.Web.Models.Screenshot", b =>
                {
                    b.HasOne("DrakthulJelita.Web.Models.WowClass", "WowClass")
                        .WithMany("Screenshots")
                        .HasForeignKey("WowClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WowClass");
                });

            modelBuilder.Entity("DrakthulJelita.Web.Models.WowClass", b =>
                {
                    b.Navigation("Screenshots");
                });
#pragma warning restore 612, 618
        }
    }
}
